#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c /home/big/.config/bspwm/sxhkdrc &
feh --bg-center /home/big/Pictures/Sfondi/Nord/wave-dark-nord.png

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# polybar &
# bspc config top_padding 27
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
